<?php

namespace App\Route;

trait ExtractRouteValuesTrait
{
    /**
     * This function was generated by Chat-GPT
     * it should extract url params from requested URL
     */
    public static function extractRouteValues($routePattern)
    {
        $url = $_SERVER['REQUEST_URI'];
        if (substr($url, -1) === '/') {
            // Remove the trailing slash
            $url = rtrim($url, '/');
        }
        
        // Escape special characters in the route pattern
        $regexPattern = preg_quote($routePattern, '#');

        // Replace placeholders like :id, :category, :slug with regex capturing groups
        $regexPattern = preg_replace_callback('/\\\:(\w+)/', function ($matches) {
            return '([^\/]+)';
        }, $regexPattern);

        // Construct the final regex pattern with anchors
        $regexPattern = '#^' . $regexPattern . '$#';

        // Initialize an array to store extracted values
        $values = [];

        // Match the URL against the regex pattern and extract values for placeholders
        if (preg_match($regexPattern, $url, $matches)) {
            // Skip the first match (which is the full URL)
            array_shift($matches);

            // Extract placeholder names from the route pattern
            preg_match_all('/:(\w+)/', $routePattern, $placeholders);
            $placeholders = $placeholders[1]; // Extracting captured group 1

            // Combine placeholders with matched values
            foreach ($placeholders as $index => $placeholder) {
                $values[$placeholder] = $matches[$index];

                // also include it in POST values to be accessible in validate functions
                $_POST[$placeholder] = $matches[$index];     
            }

            return $values;
        }

        return null; // Return null if URL does not match the pattern
    }
}
