<?php

namespace App\Route;

trait MatchRoutePatternTrait
{
    /**
     * This function was generated by Chat-GPT
     * it should take route pattern and matches with requested URL
     * returns true, false
     */
    public static function matchRoutePattern($routePattern)
    {
        if ($routePattern == "*") {
            echo "API NOT FOUND";
            die();
        }

        $url = $_SERVER['REQUEST_URI'];
        if (substr($url, -1) === '/') {
            // Remove the trailing slash
            $url = rtrim($url, '/');
        }

        // Escape special characters in the route pattern
        $regexPattern = preg_quote($routePattern, '#');

        // Replace placeholders like :id, :category, :slug with corresponding regex patterns
        $regexPattern = preg_replace_callback('/\\\:(\w+)/', function ($matches) {
            $placeholder = $matches[1];
            return '([^\/]+)'; // Default pattern (matches any characters except '/')
        }, $regexPattern);

        // Construct the final regex pattern with anchors
        $regexPattern = '#^' . $regexPattern . '$#';

        // Check if the URL matches the regex pattern
        if (preg_match($regexPattern, $url)) {
            return true;
        } else {
            return false;
        }
    }
}